kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- enrichment
- namespace.yaml
- elasticsearch.yaml
- kibana.yaml
- logstash.yaml
- logstash_pipelines

configMapGenerator:
- name: elk-environment-variables
  envs:
  - env_vars